# -*- coding: utf-8 -*-
from . import test_mail_account
from . import test_account_migration
from . import test_google_provider
from . import test_incoming_mail
from . import test_incoming_sync
from . import test_outgoing_mail
from . import test_mailbox_routing
from . import test_compose_sale_order
from . import test_compose_crm_lead
from . import test_compose_res_partner
from . import test_internal_notes
from . import test_attachments
from . import test_system_notifications
from . import test_no_mailbox_fallback
from . import test_provider_contract
from . import test_mailbox_permission
from . import test_incoming_sync_gmail
from . import test_mail_lens
from . import test_mail_coverage
