# -*- coding: utf-8 -*-
from . import test_mail_account
from . import test_account_migration
from . import test_google_provider
from . import test_imap_provider
from . import test_microsoft_provider
from . import test_incoming_mail
from . import test_internal_domains
from . import test_pan_mail_provider
from . import test_provider_migration
from . import test_onboarding
from . import test_incoming_sync
from . import test_outgoing_mail
from . import test_mailbox_routing
from . import test_compose_sale_order
from . import test_compose_crm_lead
from . import test_compose_res_partner
from . import test_internal_notes
from . import test_attachments
from . import test_system_notifications
from . import test_no_mailbox_fallback
from . import test_provider_contract
from . import test_mail_matcher
from . import test_outgoing_threading
from . import test_routing_log
from . import test_setup_flow
from . import test_mailbox_permission
from . import test_incoming_sync_gmail
from . import test_mail_lens
from . import test_mail_coverage
from . import test_mail_item
from . import test_ai_contract
from . import test_neutralized
from . import test_rename_migration
from . import test_sync_sends_nothing
from . import test_incoming_gates
from . import test_field_labels
