# -*- coding: utf-8 -*-
"""
The two indexes the thread matcher reads.

Both exist because the obvious place to store this — a Char field on
`mail.message` — cannot express what threading actually needs:

`pan.mail.message.ref` maps an RFC 5322 Message-ID onto the `mail.message` it
belongs to. One Odoo message legitimately has *several* Message-IDs: the one
Odoo generated, the one the provider assigned on the wire (Microsoft Graph
mints its own `internetMessageId` and gives no way to override it), and any id
a forwarding client re-used. A single Char field holds one of those; a
`References` chain has to resolve all of them.

`pan.mail.thread.link` maps a provider thread handle onto the Odoo record it
belongs to, *scoped to the mailbox that saw it*. Provider thread ids are not
global: Microsoft's `conversationId` is mailbox-local and derived from the
conversation topic, Gmail's `threadId` is account-local, and two mailboxes
syncing the same exchange see two different ids for it. Storing the id without
the mailbox — which is what `mail.message.x_microsoft_conversation_id` does —
means a lookup can match a thread from an entirely different mailbox.

Neither model is provider-specific. IMAP has no thread handle at all; the
matcher synthesises one from the root of the `References` chain and stores it
here like any other.
"""
import logging

from odoo import models, fields, api

from .mail_provider_client import PROVIDER_SELECTION

_logger = logging.getLogger(__name__)


class PanMailMessageRef(models.Model):
    """Every Message-ID under which one `mail.message` may be referenced."""

    _name = 'pan.mail.message.ref'
    _description = 'Email Message-ID Index'
    # Newest first: when two Odoo messages carry the same wire id (a forward of
    # our own mail comes back), the most recent one is the better parent.
    _order = 'id desc'

    message_id = fields.Char(
        string='Message-ID',
        required=True,
        index=True,
        help='RFC 5322 Message-ID, angle brackets included.',
    )
    mail_message_id = fields.Many2one(
        'mail.message',
        string='Odoo Message',
        required=True,
        ondelete='cascade',
        index=True,
    )
    source = fields.Selection(
        [('odoo', 'Generated by Odoo'), ('provider', 'Assigned by provider')],
        default='provider',
        required=True,
        help='Where this Message-ID came from. Diagnostic only; lookups treat '
             'both the same.',
    )

    _unique_ref = models.Constraint(
        'UNIQUE(message_id, mail_message_id)',
        'This Message-ID is already indexed for this message.',
    )

    @api.model
    def record(self, mail_message, message_ids, source='provider'):
        """Index `message_ids` for `mail_message`, skipping ones already known.

        Never raises: an index that fails to write must not sink the mail that
        was already delivered. The cost of a missing row is a reply that falls
        through to a weaker matching rule, not lost data.
        """
        if not mail_message or not message_ids:
            return self.browse()

        if isinstance(message_ids, str):
            message_ids = [message_ids]
        wanted = {m.strip() for m in message_ids if m and m.strip()}
        if not wanted:
            return self.browse()

        existing = set(self.sudo().search([
            ('mail_message_id', '=', mail_message.id),
            ('message_id', 'in', list(wanted)),
        ]).mapped('message_id'))

        to_create = [
            {'message_id': m, 'mail_message_id': mail_message.id, 'source': source}
            for m in wanted - existing
        ]
        if not to_create:
            return self.browse()

        try:
            # The savepoint is what makes the `except` below safe: a failed
            # INSERT leaves the PostgreSQL transaction aborted, so catching the
            # exception without rolling back would poison every later query in
            # the same cron batch.
            with self.env.cr.savepoint():
                return self.sudo().create(to_create)
        except Exception:
            _logger.exception(
                "[Mail Matcher] Could not index Message-IDs %s for mail.message %s",
                sorted(wanted), mail_message.id,
            )
            return self.browse()

    @api.model
    def lookup(self, message_id):
        """Return the `mail.message` for a Message-ID, or an empty recordset."""
        if not message_id:
            return self.env['mail.message'].browse()
        ref = self.sudo().search([('message_id', '=', message_id.strip())], limit=1)
        return ref.mail_message_id


class PanMailThreadLink(models.Model):
    """One provider thread, as seen by one mailbox, and the record it maps to.

    This is also the answer to "where did that reply end up?" — it is a list a
    human can open, filter by mailbox, and read, instead of a Char column buried
    on `mail.message`.
    """

    _name = 'pan.mail.thread.link'
    _description = 'Provider Thread Link'
    _order = 'last_seen desc, id desc'
    _rec_name = 'thread_id'

    provider = fields.Selection(
        PROVIDER_SELECTION,
        string='Provider',
        required=True,
        index=True,
    )
    mailbox_id = fields.Many2one(
        'x_microsoft.mailbox',
        string='Mailbox',
        required=True,
        ondelete='cascade',
        index=True,
        help='The mailbox that saw this thread. Thread ids are only unique '
             'within one mailbox, so this is part of the key, not metadata.',
    )
    thread_id = fields.Char(
        string='Thread ID',
        required=True,
        index=True,
        help="Provider's own thread handle (Graph conversationId, Gmail "
             "threadId), or the root Message-ID for providers that have none.",
    )
    model = fields.Char(string='Model', required=True, index=True)
    res_id = fields.Many2oneReference(
        string='Record',
        model_field='model',
        index=True,
    )
    last_message_id = fields.Many2one(
        'mail.message',
        string='Last Message',
        ondelete='set null',
        help='Most recent message seen in this thread. Used as the parent for '
             'the next reply, so a thread stays a chain instead of a fan.',
    )
    last_provider_message_id = fields.Char(
        string='Last Provider Message ID',
        help="Provider's own resource id for the most recent message in this "
             "thread — Graph's message id, Gmail's message id. Not the RFC "
             "Message-ID. Providers that can only reply *to a message* rather "
             "than *with headers* need this handle, and it belongs here rather "
             "than on mail.message because a provider resource id is scoped to "
             "one mailbox, exactly like the rest of this row.",
    )
    last_seen = fields.Datetime(
        string='Last Seen',
        default=fields.Datetime.now,
        required=True,
        index=True,
    )

    _unique_thread = models.Constraint(
        'UNIQUE(provider, mailbox_id, thread_id)',
        'This thread is already linked for this mailbox.',
    )

    @api.model
    def find_for_record(self, mailbox, model, res_id):
        """The thread this mailbox last used for a record, if any.

        The outgoing mirror of matching: before sending, this is how we learn
        which thread a reply belongs in, so the mail leaves as part of the
        conversation instead of starting a new one in the recipient's client.
        """
        if not mailbox or not model or not res_id:
            return self.browse()
        return self.sudo().search([
            ('provider', '=', mailbox.x_provider),
            ('mailbox_id', '=', mailbox.id),
            ('model', '=', model),
            ('res_id', '=', res_id),
        ], order='last_seen desc, id desc', limit=1)

    @api.model
    def record(self, mailbox, thread_id, model, res_id, message=None,
               provider_message_id=None):
        """Create or refresh the link for (mailbox, thread_id).

        Like the ref index, this never raises — a mail that was delivered must
        not be rolled back because bookkeeping failed.
        """
        if not mailbox or not thread_id or not model or not res_id:
            return self.browse()

        vals = {
            'last_seen': fields.Datetime.now(),
        }
        if message:
            vals['last_message_id'] = message.id
        if provider_message_id:
            vals['last_provider_message_id'] = provider_message_id

        try:
            # See PanMailMessageRef.record: without the savepoint, a failed
            # write here aborts the transaction the caller is still using.
            with self.env.cr.savepoint():
                return self._record(mailbox, thread_id, model, res_id, vals)
        except Exception:
            _logger.exception(
                "[Mail Matcher] Could not link thread %s on mailbox %s to %s/%s",
                thread_id, mailbox.email, model, res_id,
            )
            return self.browse()

    def _record(self, mailbox, thread_id, model, res_id, vals):
        """Upsert body of `record()`, split out so it runs inside a savepoint."""
        link = self.sudo().search([
            ('provider', '=', mailbox.x_provider),
            ('mailbox_id', '=', mailbox.id),
            ('thread_id', '=', thread_id),
        ], limit=1)
        if link:
            # A thread that moves record is a real event (a lead converted, a
            # ticket merged), so follow it rather than pinning the first answer
            # forever.
            if link.model != model or link.res_id != res_id:
                _logger.info(
                    "[Mail Matcher] Thread %s on %s moved from %s/%s to %s/%s",
                    thread_id, mailbox.email, link.model, link.res_id, model, res_id,
                )
                vals.update({'model': model, 'res_id': res_id})
            link.write(vals)
            return link

        vals.update({
            'provider': mailbox.x_provider,
            'mailbox_id': mailbox.id,
            'thread_id': thread_id,
            'model': model,
            'res_id': res_id,
        })
        return self.sudo().create(vals)
